### ISSUE TITLE
Correlation matrix calculation

### ISSUE THREAD

**Issue by Peiyao-Z** [Josie-xufan/Protein-Imputation#3]
Hi!

I found your findings interesting and was hoping to go through the process. I'm a bit confused about the correlation matrix correlation_nosaverx and correlation_saverx. Are these calculated by correlation of reap-seq data(with and without denoise) and CITEseq data (without denoise)? Also, I wonder if you obtained the correlation matrix by following correlation_coefficient.py file?

Thank you!

Peiyao

**Comment by Josie-xufan** [comment]
hi, the correlation matrices are calculated by correlation between proteins and RNAs. And we have implemented the experiments that using the RNAs before and after de-noising to calculated the correlation, named as correlation_nosaverx and correlation_saverx. In fact, the correlation is not between the two datasets. The two datasets are independently. Besides, we obtained the correlation matrix by following correlation_coefficient.py file!

**Comment by Peiyao-Z** [comment]
Hi, thanks for your reply. I'm a bit confused about the correlation_saverx and the correlation_nosaverx from  correlation_coefficient.py file (row17 and 18). I didn't find where it is defined. Is it Person correlation of RNA-seq data?
Thanks again!

**Comment by Josie-xufan** [comment]
> 

After reviewing the codes, it seems that the correlation_coefficient.py was used to compute the correlation between the prediction of protein and the ground truth of protein. While the correlation_nosaverx and the correlation_saverx should be computed by yourself. In fact, this computation is quite simple I think. If you need these files, I may send you. But I need some time to sort out since this project was finished three years ago.

**Comment by Peiyao-Z** [comment]
This makes more sense! I'll try it myself first. Thank you so much for helping me out!
